# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

module Karya
  module QueueStore
    module Internal
      class InitializerOptions
        VALID_KEYS: Array[Symbol]

        def initialize: (Hash[Symbol, Karya::backend_option_value] options) -> void
        def token_generator: () -> Karya::callable_value
        def expired_tombstone_limit: () -> Integer
        def completed_batch_retention_limit: () -> Integer
        def max_batch_size: () -> Integer
        def policy_set: () -> Backpressure::PolicySet
        def circuit_breaker_policy_set: () -> CircuitBreaker::PolicySet
        def fairness_policy: () -> Fairness::Policy
      end
    end
  end
end
