# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

module Karya
  module Primitives
    # Validates callable dependencies.
    class Callable
      @name: Symbol

      @value: Karya::callable_value

      @error_class: Karya::error_class

      def initialize: (Symbol name, Karya::callable_value value, error_class: Karya::error_class) -> void

      def normalize: () -> Karya::callable_value

      private

      attr_reader name: Symbol

      attr_reader value: Karya::callable_value

      attr_reader error_class: Karya::error_class
    end
  end
end
