module Karya
  module Primitives
    # Validates callable dependencies.
    class Callable
      @name: Symbol

      @value: (Method | Proc)

      @error_class: Karya::error_class

      def initialize: (Symbol name, (Method | Proc) value, error_class: Karya::error_class) -> void

      def normalize: () -> (Method | Proc)

      private

      attr_reader name: Symbol

      attr_reader value: (Method | Proc)

      attr_reader error_class: Karya::error_class
    end
  end
end
