module Karya
  module Primitives
    # Validates positive integer values.
    class PositiveInteger
      @name: Symbol

      @value: Karya::option_value | Array[Integer] | Hash[Symbol, Integer]

      @error_class: Karya::error_class

      def initialize: (Symbol name, Karya::option_value | Array[Integer] | Hash[Symbol, Integer] value, error_class: Karya::error_class) -> void

      def normalize: () -> Integer

      private

      attr_reader name: Symbol

      attr_reader value: Karya::option_value | Array[Integer] | Hash[Symbol, Integer]

      attr_reader error_class: Karya::error_class
    end
  end
end
