module Karya
  module Hanami
    DEFAULT_MOUNT_PATH: String

    def self.install_postgres_migration: (
      target_dir: String,
      ?migration_name: String
    ) -> String
    def self.install_mysql_migration: (
      target_dir: String,
      ?migration_name: String
    ) -> String
    def self.install_sqlite_migration: (
      target_dir: String,
      ?migration_name: String
    ) -> String

    def self.mount_path: (?prefix: String?) -> String

    def self.render_dashboard_page: (
      ?prefix: String?,
      ?title: String,
      ?asset_prefix: String?,
      ?name: String
    ) -> String
  end
end
