module Karya
  module QueueStore
    class InMemory
      module Internal
        class WorkflowChildState
          @store_state: InMemory::Internal::StoreState
          @now: Time
          @cache: Hash[String, Karya::workflow_state]

          def initialize: (
            state: InMemory::Internal::StoreState,
            now: Time,
            ?cache: Hash[String, Karya::workflow_state]
          ) -> void
          def resolve: (String batch_id) -> Karya::workflow_state

        private

          attr_reader store_state: InMemory::Internal::StoreState
          attr_reader now: Time
          attr_reader cache: Hash[String, Karya::workflow_state]

          class StateSnapshot
            @batch_id: String
            @store_state: InMemory::Internal::StoreState
            @now: Time
            @cache: Hash[String, Karya::workflow_state]

            def initialize: (
              batch_id: String,
              state: InMemory::Internal::StoreState,
              now: Time,
              cache: Hash[String, Karya::workflow_state]
            ) -> void
            def state: () -> Karya::workflow_state

          private

            attr_reader batch_id: String
            attr_reader store_state: InMemory::Internal::StoreState
            attr_reader now: Time
            attr_reader cache: Hash[String, Karya::workflow_state]
            def batch: () -> Karya::Workflow::Batch
            def registration: () -> InMemory::Internal::StoreState::WorkflowRegistration
            def jobs: () -> Array[Job]
            def child_workflows: () -> Array[Karya::Workflow::ChildWorkflowSnapshot]

            class RelationshipSnapshot
              @relationship: InMemory::Internal::StoreState::WorkflowChildren::Relationship
              @store_state: InMemory::Internal::StoreState
              @now: Time
              @cache: Hash[String, Karya::workflow_state]

              def initialize: (
                relationship: InMemory::Internal::StoreState::WorkflowChildren::Relationship,
                store_state: InMemory::Internal::StoreState,
                now: Time,
                cache: Hash[String, Karya::workflow_state]
              ) -> void
              def to_snapshot: () -> Karya::Workflow::ChildWorkflowSnapshot

            private

              attr_reader relationship: InMemory::Internal::StoreState::WorkflowChildren::Relationship
              attr_reader store_state: InMemory::Internal::StoreState
              attr_reader now: Time
              attr_reader cache: Hash[String, Karya::workflow_state]
              def child_batch_id: () -> String
              def child_state: () -> Karya::workflow_state
            end
          end
        end
      end
    end
  end
end
