module Karya
  module QueueStore
    class Redis
      module Internal
        class ReferenceQueueStoreMutex
          def initialize: (owner: Karya::QueueStore::Redis, persistence_mutex: PersistenceMutex) -> void
          def synchronize: [A] (?persist_if: ^(A) -> bool) { () -> A } -> A
          def synchronize_with_event: [A] (
            event_builder: ^(A) -> StateSnapshot::event_payload,
            ?persist_if: ^(A) -> bool
          ) { () -> A } -> A
          def read_only_synchronize: [A] () { () -> A } -> A
          def compact_snapshot: (payload: String) -> bool

          private

          attr_reader owner: Karya::QueueStore::Redis
          attr_reader persistence_mutex: PersistenceMutex
          attr_reader read_only_mutex: Karya::QueueStore::Internal::ReferenceQueueStore::Internal::ReadOnlyMutex

          def current_mutex: () -> (PersistenceMutex | Karya::QueueStore::Internal::ReferenceQueueStore::Internal::ReadOnlyMutex)
        end
      end
    end
  end
end
