module Karya
  module QueueStore
    class Redis
      module Internal
        class TokenGenerator
          def initialize: (owner: Karya::QueueStore::Redis) -> void
          def call: () -> String

          private

          attr_reader owner: Karya::QueueStore::Redis
        end
      end
    end
  end
end
