# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

module Karya
  module Internal
    module DurableQueueStore
      class OperationContext
        def initialize: (namespace: String, request: request, metadata: metadata, rows: rows) -> void

        attr_reader namespace: String
        attr_reader request: request
        attr_reader metadata: metadata
        attr_reader rows: rows
      end
    end
  end
end
