# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

module Karya
  module Internal
    module DurableQueueStore
      class OperationMutex
        def initialize: () -> void
        def synchronize: [A] (?persist_if: ^(A) -> bool) { () -> A } -> A
        def read_only_synchronize: [A] { () -> A } -> A
        def persist?: () -> bool
      end
    end
  end
end
