# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

module Karya
  module Internal
    module DurableQueueStore
      module PayloadCodec
        def self.dump: (durable_value value) -> String
        def self.decode: (String payload) -> durable_value
      end
    end
  end
end
