# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

module Karya
  module Primitives
    # Validates non-negative, finite numeric values.
    class NonNegativeFiniteNumber
      @name: Symbol

      @value: Numeric

      @error_class: Karya::error_class

      def initialize: (Symbol name, Numeric value, error_class: Karya::error_class) -> void

      def normalize: () -> Numeric

      private

      attr_reader name: Symbol

      attr_reader value: Numeric

      attr_reader error_class: Karya::error_class

      def valid?: () -> bool
    end
  end
end
