# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

class Monitor
  def initialize: () -> void

  def synchronize: [A] () { () -> A } -> A
end
