# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

module Karya
  module QueueStore
    class SQLite
      module Internal
        class DurableStateStore < Karya::Internal::DurableQueueStore::SqlStateStore
          def initialize: (connection: ::SQLite3::Database) -> void
        end
      end
    end
  end
end
