# frozen_string_literal: true

# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

source 'https://rubygems.org'

gem 'karya', path: '../karya'

gemspec

gem 'rake', require: false
gem 'reek', require: false
gem 'rspec', '~> 3.13'
gem 'rubocop', '~> 1.72', require: false
gem 'rubocop-factory_bot', require: false
gem 'rubocop-performance', require: false
gem 'rubocop-rake', require: false
gem 'rubocop-rspec', require: false
gem 'rubocop-sequel', require: false
gem 'simplecov', '~> 0.22', require: false
