#!/bin/sh

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

"${SCRIPT_DIR}/run-rubocop-all"
"${SCRIPT_DIR}/run-reek-all"
"${SCRIPT_DIR}/run-rbs-all"
"${SCRIPT_DIR}/run-node-lint-all"
"${SCRIPT_DIR}/run-rspec-unit-all"
"${SCRIPT_DIR}/run-rspec-e2e-all"
"${SCRIPT_DIR}/run-prepackage-build-all"
"${SCRIPT_DIR}/run-firefox-e2e-all"
