module Karya
  module Internal
    module MySQLSchemaCatalog
      TABLE_NAME: String

      def self.create_table_sql: () -> String
      def self.drop_table_sql: () -> String
      def self.render_active_record_migration: (
        class_name: String,
        migration_version: String
      ) -> String
      def self.render_sequel_migration: () -> String
    end
  end
end
