# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

module Karya
  module Internal
    class PayloadInput
      ABSENT: Object

      @payload: Karya::context_payload?
      @payload_keywords: Karya::context_payload
      @error_class: Karya::error_class
      @mixed_payload_message: String

      def initialize: (
        Karya::context_payload? payload,
        Karya::context_payload payload_keywords,
        payload_given: bool,
        error_class: Karya::error_class,
        mixed_payload_message: String
      ) -> void

      def to_h: () -> Karya::context_payload
    end
  end
end
