module Karya
  module Backend
    class Descriptor
      @identifier: backend_identifier

      def initialize: (identifier: backend_identifier_input) -> void

      attr_reader identifier: backend_identifier
    end
  end
end
