module Karya
  module Backend
    class InMemory
      include Base

      def initialize: (**Karya::backend_option_value options) -> void
      def identifier: () -> "in_memory"
      def build_queue_store: () -> QueueStore::InMemory
    end
  end
end
