module Karya
  module Backend
    class InMemory
      include Base

      def initialize: () -> void
      def identifier: () -> "in_memory"
      def build_queue_store: () -> QueueStore::InMemory
    end
  end
end
