module Karya
  module Backend
    class Redis
      include Base

      def initialize: (
        url: String,
        ?namespace: String,
        ?expired_tombstone_limit: Integer,
        ?completed_batch_retention_limit: Integer,
        ?max_batch_size: Integer,
        ?policy_set: Backpressure::PolicySet,
        ?circuit_breaker_policy_set: CircuitBreaker::PolicySet,
        ?fairness_policy: Fairness::Policy
      ) -> void

      attr_reader identifier: "redis"

      def build_queue_store: () -> QueueStore::Redis

      private

      attr_reader queue_store_options: Hash[Symbol, Karya::backend_option_value]
    end
  end
end
