module Karya
  module Backend
    class Selection
      KNOWN_IDENTIFIERS: Array[backend_identifier]
      IDENTIFIER_ALIASES: Hash[String, backend_identifier]

      @identifier: backend_identifier

      def self.normalize_identifier: (backend_identifier_input value) -> backend_identifier
      def self.known_identifier?: (backend_identifier_input value) -> bool

      def initialize: (backend_identifier_input value) -> void

      attr_reader identifier: backend_identifier
    end
  end
end
