# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

module Karya
  class InvalidBackendConfigurationError < Error
  end

  module Backend
    interface _QueueStoreFactoryInput
      def new: (**backend_option_value options) -> QueueStore::Base
    end

    interface _BackendClass
      def new: (**backend_option_value options) -> Base
    end

    type backend_class = ::Class & _BackendClass
  end
end
