# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

module Karya
  class InvalidBackendConfigurationError < Error
  end

  module Backend
    interface _QueueStoreFactoryInput
      def new: (
        ?token_generator: Karya::callable_value?,
        ?expired_tombstone_limit: Integer?,
        ?completed_batch_retention_limit: Integer?,
        ?max_batch_size: Integer?,
        ?policy_set: Backpressure::PolicySet?,
        ?circuit_breaker_policy_set: CircuitBreaker::PolicySet?,
        ?fairness_policy: Fairness::Policy?
      ) -> QueueStore::Base
    end

    type backend_class = ::Class
  end
end
