module Karya
  # The CLI class defines the command-line interface for the Karya gem. It uses Thor to handle command parsing and execution.
  class CLI < Thor
    def self.start: (?Array[String] given_args, ?Hash[Symbol | String, Karya::cli_option_value] config) -> nil

    def self.header: () -> ::String

    def version: () -> nil

    def help: (?String command) -> nil

    def worker: (*String queues) -> nil
  end
end
