# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

module Karya
  module QueueStore
    class MySQL
      module Internal
        class PersistenceMutex
          def initialize: (connection: ::Mysql2::Client, owner: Karya::QueueStore::MySQL) -> void
          def ensure_schema: () -> nil
          def run_mutation: [T] (?operation_name: Symbol?) { () -> T } -> T
          def run_reserve: [T] (?operation_name: Symbol?) { () -> T } -> T
          def run_read_only: [T] (?operation_name: Symbol?) { () -> T } -> T
        end
      end
    end
  end
end
